#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py spectacular --file portfolio/api/schema.yml
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
