# Generated by Django 5.0.8 on 2024-09-03 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('duration', models.FloatField(blank=True, default=None, null=True)),
                ('elevation', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('trimp', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
