# Generated by Django 5.0.8 on 2024-08-28 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('minimum_heart_rate', models.IntegerField(default=60)),
                ('maximum_heart_rate', models.IntegerField(default=190)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('duration', models.FloatField(blank=True, default=None, null=True)),
                ('elevation', models.FloatField(blank=True, default=None, null=True)),
                ('trimp', models.IntegerField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitness.point')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cadence', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.activity'),
        ),
    ]
