# Generated by Django 5.0.8 on 2024-09-03 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitness', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('minimum_heart_rate', models.IntegerField(default=60)),
                ('maximum_heart_rate', models.IntegerField(default=190)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitness.point')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cadence', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.activity'),
        ),
    ]
