# Generated by Django 5.0.8 on 2024-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
