from rest_framework import serializers


class CoordinatesSerializer(serializers.Serializer): ...


class LineGeometrySerializer(serializers.Serializer): ...


class LinePropertiesSerializer(serializers.Serializer): ...


class LineSerializer(serializers.Serializer): ...


class PointGeometrySerializer(serializers.Serializer): ...


class PointPropertiesSerializer(serializers.Serializer): ...


class PointSerializer(serializers.Serializer): ...


class GeoJSONSerializer(serializers.Serializer): ...
