name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Construct .envs
        run: |
          mkdir -p .envs/.local/
          echo "USE_DOCKER=yes" >> .envs/.local/.django
          echo "IPYTHONDIR=/app/.ipython" >> .envs/.local/.django
          echo "REDIS_URL=${RedisURL}" >> .envs/.local/.django
          echo "CELERY_FLOWER_USER=${CeleryUser}" >> .envs/.local/.django
          echo "CELERY_FLOWER_PASSWORD=${CeleryPassword}" >> .envs/.local/.django

          echo "POSTGRES_HOST=${PostgresHost}" >> .envs/.local/.postgres
          echo "POSTGRES_PORT=${PostgresPort}" >> .envs/.local/.postgres
          echo "POSTGRES_DB=${PostgresDB}" >> .envs/.local/.postgres
          echo "POSTGRES_USER=${PostgresUser}" >> .envs/.local/.postgres
          echo "POSTGRES_PASSWORD=${PostgresPassword}" >> .envs/.local/.postgres
        env:
          RedisURL: ${{ secrets.REDISURL }}
          CeleryUser: ${{ secrets.CELERYUSER }}
          CeleryPassword: ${{ secrets.CELERYPASSWORD }}
          PostgresHost: ${{ secrets.POSTGRESHOST }}
          PostgresPort: ${{ secrets.POSTGRESPORT }}
          PostgresDB: ${{ secrets.POSTGRESDB }}
          PostgresUser: ${{ secrets.POSTGRESUSER }}
          PostgresPassword: ${{ secrets.POSTGRESPASSWORD }}

      - name: Build the Stack
        run: docker compose -f docker-compose.local.yml build django

      - name: Build the docs
        run: docker compose -f docker-compose.docs.yml build docs

      - name: Run DB Migrations
        run: docker compose -f docker-compose.local.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        run: docker compose -f docker-compose.local.yml run django pytest

      - name: Run Node Tests
        run: docker compose -f docker-compose.local.yml run node npm test

      - name: Run Cypress Tests
        run: docker compose -f docker-compose.local.yml -f docker-compose.cypress.yml run cypress npm run start-e2e

      - name: Tear down the Stack
        run: docker compose -f docker-compose.local.yml -f docker-compose.cypress.yml down
