/* tslint:disable */
/* eslint-disable */
/**
 * portfolio API
 * Documentation of API endpoints of portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Activity
 */
export interface Activity {
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  readonly uuid: string;
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  readonly owner: number;
  /**
   *
   * @type {string}
   * @memberof Activity
   */
  readonly name: string;
  /**
   *
   * @type {Date}
   * @memberof Activity
   */
  readonly time: Date;
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  readonly distance: number | null;
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  readonly duration: number | null;
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  readonly elevation: number | null;
  /**
   *
   * @type {number}
   * @memberof Activity
   */
  readonly trimp: number | null;
}

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
  if (!('uuid' in value) || value['uuid'] === undefined) return false;
  if (!('owner' in value) || value['owner'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('time' in value) || value['time'] === undefined) return false;
  if (!('distance' in value) || value['distance'] === undefined) return false;
  if (!('duration' in value) || value['duration'] === undefined) return false;
  if (!('elevation' in value) || value['elevation'] === undefined) return false;
  if (!('trimp' in value) || value['trimp'] === undefined) return false;
  return true;
}

export function ActivityFromJSON(json: any): Activity {
  return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Activity {
  if (json == null) {
    return json;
  }
  return {
    uuid: json['uuid'],
    owner: json['owner'],
    name: json['name'],
    time: new Date(json['time']),
    distance: json['distance'],
    duration: json['duration'],
    elevation: json['elevation'],
    trimp: json['trimp'],
  };
}

export function ActivityToJSON(
  value?: Omit<
    Activity,
    | 'uuid'
    | 'owner'
    | 'name'
    | 'time'
    | 'distance'
    | 'duration'
    | 'elevation'
    | 'trimp'
  > | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
