/* tslint:disable */
/* eslint-disable */
/**
 * portfolio API
 * Documentation of API endpoints of portfolio
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivitySVGPoints
 */
export interface ActivitySVGPoints {
    /**
     * 
     * @type {number}
     * @memberof ActivitySVGPoints
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof ActivitySVGPoints
     */
    y: number;
}

/**
 * Check if a given object implements the ActivitySVGPoints interface.
 */
export function instanceOfActivitySVGPoints(value: object): value is ActivitySVGPoints {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function ActivitySVGPointsFromJSON(json: any): ActivitySVGPoints {
    return ActivitySVGPointsFromJSONTyped(json, false);
}

export function ActivitySVGPointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivitySVGPoints {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function ActivitySVGPointsToJSON(value?: ActivitySVGPoints | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

